services:
  portfolio-ws:
    build:
      context: .
      dockerfile: DockerfileDev
    container_name: portfolio-ws
    ports:
      - 5010:5010
    env_file:
      - .env.development
    volumes:
      - ./data:/app/data
